Fix TypeError (executor.py and future.py)
The FutureWrapper.result function name has been changed to resolve errors caused by duplicate function names.

FutureWrapper.result -> FutureWrapper.get_result

[2022-01-22 10:30:02.230 ERROR    executor] Unhandled exception while checking connections
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sawtooth_validator/execution/executor.py", line 465, in _check_connections
    fut.result(timeout=10)
  File "/usr/lib/python3/dist-packages/sawtooth_validator/networking/future.py", line 55, in result
    return self._future.result(timeout=timeout)
TypeError: result() got an unexpected keyword argument 'timeout'